version: '3'
services:
  rancher-server:
    image: rancher/rancher:latest
    container_name: rancher-server
    ports:
      - "8090:80"
      - "8444:443"
    restart: unless-stopped
    privileged: true
    environment:
      - CATTLE_SYSTEM_CATALOG=bundled
      - CATTLE_AUTH=local
      - CATTLE_PASSWORD=
