kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mesh-storage-hdd
  annotations:
    # disable this default storage class by setting this annotation to false.
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
parameters:
  type: pd-standard
  fstype: ext4
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mesh-storage-ssd
  annotations:
    # disable this default storage class by setting this annotation to false.
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
parameters:
  type: pd-ssd
  fstype: ext4
